---

- set_fact:
    nessus_server_url: "{{ secret_text | json_query('nessus_server_url') }}"
    nessus_server_port: "{{ secret_text | json_query('nessus_server_port') }}"
    nessus_agent_key: "{{ secret_text | json_query('nessus_agent_key') }}"

- name: RedHat
  set_fact:
    package_folder: rpm/rhel
    package_type: rpm
  when: ansible_facts['distribution']|lower == 'redhat' 

- name: Amazon
  set_fact:
    package_type: amz
    package_folder: rpm/amazon
  when: ansible_facts['distribution']|lower == 'amazon' 

- name: Ubuntu and debian
  set_fact:
    package_type: deb
    package_folder: deb
  when: ansible_facts['os_family']|lower == 'debian'

- name: Windows Server and Workstation
  set_fact:
    package_type: win
    package_folder: win
  when: ansible_facts['os_family']|lower == 'windows'

- name: Check if installer exists
  stat:
    path: "{{ role_path }}/files/{{ nessus_installer_file[package_type] }}"
  register: stat_result
  delegate_to: localhost
  become: false

- name: Download Binaries from S3 
  amazon.aws.s3_object:
    bucket: sectools-installation-artifacts
    object: "{{ package_folder }}/{{ nessus_installer_file[package_type] }}"
    dest: "{{ role_path }}/files/{{ nessus_installer_file[package_type] }}"
    mode: get
    access_key: "{{ access_key }}"
    secret_key: "{{ secret_key }}"
    session_token: "{{ session_token }}"
  delegate_to: localhost
  when: not stat_result.stat.exists
  become: false

- name: RedHat
  include_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Ubuntu and debian
  include_tasks: ubuntu.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Windows Server and Workstation
  include_tasks: win.yml
  when: ansible_facts['os_family']|lower == 'windows'
  
